dataset_name: 'liver'
dataset_path: '$CUTS_ROOT/data/liver/'
supervised_network: 'nnunet'
model_save_path: '$CUTS_ROOT/checkpoints/supervised_liver_nnunet_seed2022.pty'
output_save_path: '$CUTS_ROOT/results/liver_seed2022/'
log_folder: '$CUTS_ROOT/logs'
learning_rate: 1e-3
weight_decay: 1e-4
max_epochs: 200
patience: 10
batch_size: 15
num_workers: 8
random_seed: 2022
train_val_test_ratio: '7:1:2'
pretrained: False